aboutoflinux: true
aboutpcs: true
abysmalrobloxgames: true
abysmalthetoptennersandlists: true
adorefacebookusers: true
aiytf: 'wiki.abyogsms.org.in'
albakiyye: true
alchemy: true
alphabeton: true
anamnesis: true
aradia: true
arcaear: true
asvany: true
atlasinternational: true
badquotevusers: true
barishal: true
bootyfarm: true
campaignlab: 'wiki.campaign-labour.org'
cantonian: true
carolinaroots: true
ccl: 'wiki.counterculturelabs.org'
cdcrmh: true
cfd: true
charsheets: true
chuckecheeses: true
ckmp: true
climatetest: 'wiki.climatechange.ai'
closinglogosgroup: true
cmgi: true
cnkwiki: true
cogitopedie: true
comiccrossroads: true
commons: true
community: true
concordance: true
const: true
cookierun: true
crp: true
csydes: true
cyberneticeye: true
cymerwiki: true
dasschwarzeauge: true
degreesoflewdity: true
delightfulmusicandsongs: true
destruipedia: true
discordinfo: true
dlt: true
documentcontrol: 'news.famepedia.co.in'
dreadfulmusic: true
dreamsit: 'dreamsit.com.br'
dreamverse: true
dr: true
earthcraft: true
ecoepi: true
ektheto: true
electowiki: 'electowiki.org'
eleria: true
emilysdentistry: true
esgyaanipedia: 'es.gyaanipedia.com'
estenpaix: true
eurekia: true
evovision: true
fallendoll: 'www.erikapedia.com'
fanmadeanimals: true
fantasypedia: true
fillariwiki: true
freesoftwarepedia: true
ftvs: true
garbagelegos: true
generali80wiki: true
genship: true
giantess: true
gpw: true
greatamazingusefulsoftware: true
greatdeviantartist: true
guayoyophysics: true
gyaanipedia: 'en.gyaanipedia.com'
hammerbro101: true
heroes: true
historyworld: true
ilias: true
illidanstormrageaps: true
indianwiki: true
infectoped: 'infectowiki.com'
inforevival: true
ingen: true
interucronias: true
interwebpedia: true
ipoly: true
islamicdroos: true
ivazedu: true
japan: true
jcs: 'wiki.gesamtschule-nordkirchen.de'
junapedia: true
kaohsiung: true
khatik: 'en.famepedia.co.in'
latinfa: true
lf13videos: true
lggyaanipedia: 'lg.gyaanipedia.com'
lifeasakaiju: true
lilypond: true
limpd: true
limzhihaowinston: true
ls: true
madeirapedia: true
madelinethecoolgirl: true
magic: 'vedopedia.witches-empire.com'
megawiki: true
meingarten: true
melayu: true
mercury203: true
mergenymphs: true
messengergeek: true
meta: true
mikekilitterbox: true
mikrodev: 'wiki.mikrodev.com'
milvagox: true
mineralworld: true
mncn: true
moderaterightpedia: true
monarchists: 'monarchists.wiki'
morava: true
moretypedesign: true
moviepedia: true
mysqltalk: true
ndg: 'ndg.nenawiki.org'
neely: true
nenawiki: 'nenawiki.org'
nernasystem: true
netflix: true
neurostat: true
nintendogames: true
nonbinary: 'nonbinary.wiki'
nonciclopedia: 'nonciclopedia.org'
onepiecebountyrush: true
onepiece: true
ourheroacademia: true
outrageouslyabysmaleventsinhistory: true
paikallishistoriawiki: true
partituricoraleromanesti: true
perfectrobloxgames: true
phgalaxy: 'en.phgalaxy.xyz'
philosophystoreoo: true
pm: true
polskajest: true
polytope: true
projectsekai: true
pseudociencia: true
rabocheyedelo: true
reverseatrociousyoutubers: true
revit: true
reviwiki: 'reviwiki.info'
rom1d13: true
rothwell: 'www.rothwell-leeds.co.uk'
santawiki: true
sciencewiki: true
scpwikimc: true
secwiki: 'wiki.kali-team.cn'
segmarian: true
sevenwonders: true
skgy: true
skmedia: true
smyslenawiki: true
soe: true
soft: true
solara: 'spcodex.wiki'
soshirenmei: true
spaceporto: true
spongypedia: true
sporepedia: true
ssmc: true
stateof: true
sxzwiki: true
sympoliteia: true
takisandyoshiworld: true
ted52: true
template: true
test2: true
test: 'publictestwiki.com'
thehushhushsaga: true
thekingdomsmp: true
thenewark: true
theresnothingbetter: true
theschizozone: true
thesciencearchives: true
theterribletwo: true
thetriplets: true
tmerebooted: true
tomica: true
toms: true
touhoujuan: true
touhouwiki: true
transformers: true
trolling: true
ucmg: 'wiki.ucmg.ml'
umipedia: true
underpressure: true
ungame: true
uniwiki: true
unquotable: true
venciclopedia: true
vilemaxim: true
vixenwars: true
vnenderbot: true
wanilia: true
wikibeats: 'wikibeats.net'
wikibunpou: true
wikicristianismo: true
wikifandompedia: true
wikiheze: true
wikikids: true
wikisai: true
wikiseedarchives: true
wikitheos: true
wikitrivia: true
willdonahue: true
wiseanswers: true
worldsongcontestgem: true
xxswiki: true
yazz: true
youngwitch: true