aboutoflinux: true
aboutpcs: true
abysmalthetoptennersandlists: true
adorefacebookusers: true
aiytf: 'wiki.abyogsms.org.in'
albakiyye: true
alphabeton: true
anamnesis: true
aradia: true
arcaear: true
badquotevusers: true
barishal: true
bootyfarm: true
campaignlab: 'wiki.campaign-labour.org'
cantonian: true
carolinaroots: true
ccl: 'wiki.counterculturelabs.org'
chuckecheeses: true
climatetest: 'wiki.climatechange.ai'
closinglogosgroup: true
cnkwiki: true
comiccrossroads: true
commons: true
community: true
concordance: true
const: true
cookierun: true
csydes: true
cyberneticeye: true
degreesoflewdity: true
delightfulmusicandsongs: true
destruipedia: true
discordinfo: true
dlt: true
documentcontrol: 'news.famepedia.co.in'
dreadfulmusic: true
dreamsit: 'dreamsit.com.br'
dreamverse: true
dr: true
earthcraft: true
ektheto: true
electowiki: 'electowiki.org'
esgyaanipedia: 'es.gyaanipedia.com'
evovision: true
fallendoll: 'www.erikapedia.com'
fanmadeanimals: true
fantasypedia: true
fillariwiki: true
freesoftwarepedia: true
ftvs: true
garbagelegos: true
giantess: true
greatamazingusefulsoftware: true
greatdeviantartist: true
gyaanipedia: 'en.gyaanipedia.com'
hammerbro101: true
heroes: true
ilias: true
indianationstateswiki: true
indianwiki: true
infectoped: 'infectowiki.com'
ingen: true
interucronias: true
ipoly: true
islamicdroos: true
japan: true
junapedia: true
kaohsiung: true
khatik: 'en.famepedia.co.in'
latinfa: true
lf13videos: true
lggyaanipedia: 'lg.gyaanipedia.com'
lifeasakaiju: true
lilypond: true
limzhihaowinston: true
magic: 'vedopedia.witches-empire.com'
megawiki: 'data.maantietaja.org'
meingarten: true
melayu: true
mercury203: true
mergenymphs: true
messengergeek: true
meta: true
mikrodev: 'wiki.mikrodev.com'
milvagox: true
moderaterightpedia: true
monarchists: 'monarchists.wiki'
morava: true
moretypedesign: true
moviepedia: true
mysqltalk: true
nenawiki: 'nenawiki.org'
nernasystem: true
netflix: true
neurostat: true
nintendogames: true
nonbinary: 'nonbinary.wiki'
nonciclopedia: 'nonciclopedia.org'
onepiecebountyrush: true
onepiece: true
onibus: true
ourheroacademia: true
outrageouslyabysmaleventsinhistory: true
paikallishistoriawiki: true
partituricoraleromanesti: true
perfectrobloxgames: true
phgalaxy: 'en.phgalaxy.xyz'
pm: true
polskajest: true
polytope: true
projectsekai: true
pseudociencia: true
rabocheyedelo: true
revit: true
reviwiki: 'revi.wiki'
rom1d13: true
rothwell: 'www.rothwell-leeds.co.uk'
santawiki: true
sciencewiki: true
scpwikimc: true
secwiki: 'wiki.kali-team.cn'
segmarian: true
shekh: true
skgy: true
skmedia: true
smyslenawiki: true
soe: true
soft: true
solara: 'spcodex.wiki'
soshirenmei: true
spaceporto: true
spongypedia: true
sporepedia: true
ssmc: true
sxzwiki: true
sympoliteia: true
takisandyoshiworld: true
ted52: true
template: true
test2: true
test: 'publictestwiki.com'
thehushhushsaga: true
thekingdomsmp: true
thenewark: true
theresnothingbetter: true
theschizozone: true
thesciencearchives: true
theterribletwo: true
thetriplets: true
tmerebooted: true
tomica: true
touhoujuan: true
touhouwiki: true
transformers: true
transpedia: true
trolling: true
ucmg: 'arquivo.ucmg.ml'
umipedia: true
ungame: true
uniwiki: true
unquotable: true
vilemaxim: true
vitaepedia: true
vixenwars: true
vnenderbot: true
wanilia: true
wikibeats: 'wikibeats.net'
wikibunpou: true
wikicristianismo: true
wikifandompedia: true
wikikids: true
wikisai: true
wikiseedarchives: true
wikitheos: true
wikitrivia: true
willdonahue: true
wiseanswers: true
worldsongcontestgem: true
yazz: true
youngwitch: true