2b2t: true
50beardsofgrey: true
690squadron: true
abortopedia: true
acqint: true
adlc: true
aeross: true
afterworld: true
agilebook: true
aisg: true
aktpos: true
alanoccv: true
ale: true
algopedia: true
allthetropes: 'allthetropes.org'
allwikis: true
alternatehistory: true
alternatesporthistory: true
altuspoliticsproject: true
altverse: true
alwiki: true
amazingyoutubers: true
anachronoxwiki: true
ancyclopedia: true
andusan: true
angelwise: true
aniwotawiki: true
anothereden: true
antrozoologia: true
apcwiki: 'www.apcwiki.org'
apneuvereniging: true
apuntes: true
arefepva: true
arphilosophy: true
ar: true
asgyaanipedia: true
astrobiology: 'encyclopediaofastrobiology.org'
atlasinternational: true
atm: true
atrociousdeviants: true
atrociousfandomusers: true
atrociousyoutubers: true
australiasim: true
awesomegames: true
awfulmovies: true
ayrshire: true
ayurbooks: true
basura: true
bch: true
bearwiki: true
besttvshows: true
betapurple: true
bgo: true
biblicalwiki: true
bigcartoon: true
bigforest: true
bildung: true
biu: true
blepia: true
blooperwiki: true
bloowiki: true
bngyaanipedia: 'bn.gyaanipedia.co.in'
bogdan: true
bonessdiving: 'wiki.bonessdiving.club'
bonziworld: true
borost: true
bpa: true
breedersofthenephelym: true
browndust: true
brynda1231: true
bsc: true
bst: true
bubba: true
buddypedia: true
bunker401: true
bus: true
byblopedia: true
caestaron: true
calibro: true
campaignlab: 'wiki.campaign-labour.org'
cantorij: true
cartesium: true
carvalhopedia: 'wiki.casadocarvalho.net'
casuarina: true
cbhssjb: true
cccp: true
cdc: true
central: true
chimaera: true
christipedia: true
civclassic: true
civitas: true
ckc: true
clineclass: true
cloudconstruct: true
cmhoc: true
cnv: true
codexamica: true
commonsgyaanipedia: 'commons.gyaanipedia.co.in'
commonswiki: true
communitycentralbympteam: true
communitydirectedsupport: true
concepts: true
conseildesvoleurs: true
conservapedia: true
conservipedia: true
const: true
corepedia: true
corro: true
corsarius: true
corydoctorow: true
craedopedia: true
crappygames: true
crazybloxianempireinfo: true
credco: true
crest: true
crimescience: 'crimesciencewiki.org'
critalenca: true
csnimsbordeaux: true
ctfoundry: true
cuttingroom: true
cyberlaw: true
dakhilcommunity: true
dalar: true
decrypted: 'decrypted.wiki'
destinos: true
diaroleplays: true
didapro: 'encyclopedie.didactiqueprofessionnelle.org'
differenthistory: true
dish: true
dobots: 'wiki.dobots.nl'
dofo: true
doin: true
doomsdaydebunked: true
dragpedia: 'drag.lgbt'
dreddbook: true
drones4all: 'wiki.drones4nature.info'
dwe: true
dwplive: 'wiki.dwplive.com'
dyrn: true
eaddemos: true
earthian: true
ecoepi: true
ecype: true
edw: true
eerstelijnszones: 'www.eerstelijnszones.be'
electowiki: 'electowiki.org'
elpoderdelpueblo: true
encyclopediaikonia: true
encyclopediainsania: true
encyclopediamemeia: true
encyclopedia: true
enigma: true
environmentaljustice: true
eon: true
epicerieissy: true
epicseven: true
espiral: 'espiral.org'
eva: true
exocortex: 'exocortex.sillyendpoints.com'
fagyaanipedia: 'fa.gyaanipedia.co.in'
fantasia: true
ferahistoria: true
feu: 'froggy.info'
fictionfoundry: true
fifam: true
fikcyjnatv: true
fkkfan: true
flawlessfandomusers: true
fluxordev: true
fmbv: true
fna: true
foodsharinghamburg: true
forbidden: true
fortnite: true
freevandalism: true
futurewiki: true
gasepedia: true
geirpedia: true
genealog: true
genship: true
gen: true
gepacoassoculture: true
gepacobiodiv: true
gfi: true
ghhs: true
giantess: true
giletjaune: true
gipedia: true
gkatom: true
glueckssammler: true
godottuts: true
grandtheftauto: true
graymainewiki: true
grdarchive: true
greatcharacterswiki: true
greatestmovies: true
grsupercars: true
gsb: true
gtnh: true
guiaslocais: 'guiasdobrasil.com.br'
guidefrance: true
gyaanipedia: 'en.gyaanipedia.co.in'
gze: true
hackdown: 'wiki.hackdown.me'
hamfem: true
harrypotter: true
haxballportugal: true
hgwiki: true
hiawa: true
higyaanipedia: 'hi.gyaanipedia.co.in'
hirondepedia: true
histo28: true
hjelpemidler: true
hkimgboard: true
hmangadoujinshiproject: true
hobbies: true
holonet: 'holonet.pw'
horizon: true
hypotheticalwiki: true
idolmaster: true
ilasoram: true
imaginarypedia: true
imagine: true
inazumaeleven: true
incorrecttohowiki: true
indiasim: true
indrema: true
indrik: true
infamousreign: true
infectoped: 'infectowiki.com'
info: true
ininfinitum: true
internetpedia: true
internobrasilguiaslocais: 'interno.guiasdobrasil.com.br'
intrabase: true
ipedia: 'islamkosh.tk'
ipoly: true
israelhistory: true
isv: true
izanagi: true
jalproverse: true
jawptest: true
jcs: 'wiki.gesamtschule-nordkirchen.de'
jeong000307: true
jeongi: true
jiangye: true
jordepedia: true
joustro: true
jrichard: true
jwiki: true
jw: 'www.jawright.cc'
kai: true
kapuluan: true
karniaruthenia: true
kassai: true
kgb: true
kinderacic: true
kirarafantasia: true
kkutu: 'kkutu.wiki'
klimagruppe: true
kngyaanipedia: 'kn.gyaanipedia.co.in'
kosatsuwiki: true
krebs: true
kuoyue: true
kurwowizja: true
kybermc: 'wiki.kybermc.tk'
lapolitics: true
lastcrew: true
legina: true
legionasgard: true
legrandmessager: true
lexwiki: true
limpd: true
limzhihaowinston: true
lingnlang: true
lionhearttales: true
livingdeadman: true
loathsomecharacters: true
loolomis: true
lovelive: true
ls: true
lunfeng: true
lwdfoundation: true
m00se: true
maccnyc: 'wiki.macc.nyc'
magez: true
magnaverse: true
mahuset: true
maiasongcontest: true
make717: 'wiki.make717.org'
malaysia: 'www.mywiki.icu'
mamsprawdzone: true
marinebiodiversitymatrix: 'marinebiodiversitymatrix.org'
marioserieswiki: true
marthaspeaks: true
mattsworldbuilding: true
mdcxlab: true
mdestech: true
meaasta: true
mediateca: true
meregos: 'meregos.com'
metagyaanipedia: 'meta.gyaanipedia.co.in'
meta: true
metrocraft: true
mgyaanipedia: 'mg.gyaanipedia.co.in'
microtonal: true
mikipedia: true
mikrodev: 'wiki.mikrodev.com'
minecraftsmp: true
miningpromies: true
mnzp: true
modelausparl: true
modelshipreference: true
modesofdiscourse: 'www.modesofdiscourse.com'
modular: true
momentum: true
momobomber: true
monarchists: 'monarchists.wiki'
mrgyaanipedia: 'mr.gyaanipedia.co.in'
mtfhrt: true
mundoparalelo: true
musicarchive: true
mystara: true
n2go: true
nanatsunotaizai: true
nano: true
naod: true
naruto: true
navmed: true
ndg: 'ndg.nenawiki.org'
nenawiki: 'nenawiki.org'
nerdzone: true
netawiki: true
netazar: 'www.netazar.org'
netspace: true
newarkmanor: true
newknowledge: true
newsnow: 'newsnow.wiki'
nextlevelwiki: 'wiki.lbcomms.co.za'
nexusaeternia: true
nimrodnero: true
nintendogs: true
noalatala: true
nonbinary: 'nonbinary.wiki'
nonciclopedia: 'nonciclopedia.org'
norskrap: true
northhub: true
notasdeproducao: true
novaya: true
novelists: true
nrp1: true
nutrition: true
nvc: true
nvliu: true
nxwiki: true
nychousingwiki: true
oecumene: 'oecumene.org'
ofthevampire: true
omnis: true
oncproject: true
opengovpioneers: true
openpolicy: true
opmi: true
orangist: true
oryza: true
ourmxfest: true
oursource: true
overon: true
pactrack: true
pagyaanipedia: 'pa.gyaanipedia.co.in'
paliwiki: true
pam: true
pandorauniverse: true
paodeaoda: true
paranormalpedia: true
parents: true
paulsec: true
pb2stof: true
pbg: true
pcarchitect: 'pc-architect.tk'
pcbs: true
peace: true
perfume: 'prfm.wiki'
permanentfuturelab: 'permanentfuturelab.wiki'
perrexipedia: true
perthowiki: true
petctviewer: true
petersburg: true
philosiverse: true
physics: true
plasticssongcontest: true
plazmaburst: true
pmav: true
podpedia: 'podpedia.org'
pokemonpedia: true
popnmusic: true