2b2t: true
2ndenlightenment: true
50beardsofgrey: true
abortopedia: true
absurdopedia: true
abysmalrobloxgames: true
adlc: true
adrianwest: true
aebyp: true
aeross: true
afterworld: true
ahrgtest: true
airportexpressline: true
aktpos: true
alanoccv: true
algopedia: true
algowiki: true
allthetropes: 'allthetropes.org'
allwikis: true
alternatehistory: true
alternatesporthistory: true
altuspoliticsproject: true
altverse: true
alwiki: true
amazingyoutubers: true
anachronoxwiki: true
ancyclopedia: true
angelwise: true
animanga: true
animeshoes: true
anothereden: true
antlersg: 'wiki.antlersg2.info'
antrozoologia: true
apcwiki: 'www.apcwiki.org'
apneuvereniging: true
apuntes: true
arefepva: true
arphilosophy: true
ar: true
asc: true
asexual: true
asgyaanipedia: true
astrobiology: 'encyclopediaofastrobiology.org'
atlasinternational: true
atpl: true
atrociousdeviants: true
atrociousfandomusers: true
atrociousyoutubers: true
australiasim: true
automobilepedia: true
awesomegames: true
awfulmovies: true
ayrshire: true
ayurbooks: true
basura: true
bch: true
bearwiki: true
besttvshows: true
betapurple: true
bgo: true
biblicalwiki: true
bigcartoon: true
bigforest: true
biu: true
blepia: true
blobcatdict: true
blobcats: true
blooperwiki: true
bngyaanipedia: 'bn.gyaanipedia.co.in'
bogdan: true
bondsofmarrak: true
bonessdiving: 'wiki.bonessdiving.club'
bonzipedia: true
bonziworld: true
borost: true
bpa: true
breedersofthenephelym: true
browndust: 'browndust.wiki'
brynda1231: true
bsaikatsu: true
bsc: true
bst: true
bubba: true
buddypedia: true
bullshitsystems: 'wiki.bullshit.systems'
bus: true
c105op: true
calibro: true
campaignlab: 'wiki.campaign-labour.org'
cartesium: true
carvalhopedia: 'wiki.casadocarvalho.net'
casthog: true