aarthalopedia: true
aboutoflinux: true
aboutpcs: true
adorefacebookusers: true
aiytf: 'wiki.abyogsms.org.in'
albakiyye: true
alphabeton: true
amaririsu: true
arcaear: true
badquotevusers: true
barishal: true
biblestrength: 'biblestrength.org'
bootyfarm: true
campaignlab: 'wiki.campaign-labour.org'
cantonian: true
carolinaroots: true
ccl: 'wiki.counterculturelabs.org'
chuckecheeses: true
climatetest: 'wiki.climatechange.ai'
closinglogosgroup: true
comiccrossroads: true
comitesdeluta: true
commons: true
community: true
concordance: true
const: true
cookierun: true
crpteam: true
csydes: true
deantsawiki: true
degreesoflewdity: true
delightfulmusicandsongs: true
destruipedia: true
discordinfo: true
dlt: true
documentcontrol: 'famedata.org'
dreamsit: 'dreamsit.com.br'
dreamverse: true
dr: true
earthcraft: true
egoish: 'egoish.org'
ektheto: true
electowiki: 'electowiki.org'
esgyaanipedia: 'es.gyaanipedia.com'
evovision: true
fallendoll: 'www.erikapedia.com'
fanmadeanimals: true
fantastictoys: true
fantasypedia: true
fillariwiki: true
freesoftwarepedia: true
ftvs: true
garbagelegos: true
giantess: true
goodquotevusers: true
greatamazingusefulsoftware: true
gyaanipedia: 'en.gyaanipedia.com'
hammerbro101: true
indianationstateswiki: true
infectoped: 'infectowiki.com'
ingen: true
interucronias: true
ipoly: true
islamicdroos: true
jagyonwiki: true
japan: true
junapedia: true
kaohsiung: true
khatik: 'en.famepedia.org'
latinfa: true
lf13videos: true
lggyaanipedia: 'lg.gyaanipedia.com'
lifeasakaiju: true
life: true
lilypond: true
limzhihaowinston: true
magic: 'vedopedia.witches-empire.com'
megawiki: 'data.maantietaja.org'
meingarten: true
melayu: true
mercury203: true
mergenymphs: true
messengergeek: true
meta: true
mikrodev: 'wiki.mikrodev.com'
milvagox: true
moderaterightpedia: true
monarchists: 'monarchists.wiki'
moretypedesign: true
moviepedia: true
mwpedia: true
mylittlefandompolska: true
mysqltalk: true
nenawiki: 'nenawiki.org'
nernasystem: true
netflix: true
neurostat: true
nihonmyouzipedia: true
nintendogames: true
nmfwiki: true
nonbinary: 'nonbinary.wiki'
nonciclopedia: 'nonciclopedia.org'
noosfera: true
nspedia: true
onepiecebountyrush: true
onepiece: true
onibus: true
paikallishistoriawiki: true
partituricoraleromanesti: true
perfectrobloxgames: true
phgalaxy: 'en.phgalaxy.xyz'
pm: true
polskajest: true
polytope: true
projectsekai: true
pseudociencia: true
pullbackcars: true
rabocheyedelo: true
racetracks: true
radiantpets: true
revit: true
reviwiki: 'revi.wiki'
risapedia: 'es.nocyclo.tk'
robloxpiggy: true
rothwell: 'www.rothwell-leeds.co.uk'
rubikcube: true
sciencewiki: true
scpwikimc: true
secwiki: 'wiki.kali-team.cn'
segmarian: true
smyslenawiki: true
sof: true
solara: 'spcodex.wiki'
soshirenmei: true
spaceporto: true
spiritsofargonothwiki: true
spongypedia: true
sxzwiki: true
sympoliteia: true
takisandyoshiworld: true
tankipedia: true
template: true
test: 'publictestwiki.com'
thekingdomsmp: true
thesciencearchives: true
thetriplets: true
tomica: true
transformers: true
ucmg: 'arquivo.ucmg.ml'
umipedia: true
vanhocviet: true
vgportdb: true
vitaepedia: true
vivapinatagameplay: true
vixenwars: true
vnenderbot: true
wanilia: true
weatherradio: true
wiiki: true
wikibeats: 'wikibeats.net'
wikibunpou: true
wikicristianismo: true
wikifandompedia: true
wikihood: true
wikikids: true
wikisai: true
wikiseedarchives: true
wikitrivia: true
worldsongcontestgem: true
yazz: true