2b2t: true
50beardsofgrey: true
690squadron: true
abortopedia: true
absurdopedia: 'absurdopedia.wiki'
acqint: true
adlc: true
aeross: true
afterworld: true
agilebook: true
aisg: true
aktpos: true
alanoccv: true
ale: true
algopedia: true
allthetropes: 'allthetropes.org'
allwikis: true
alternatehistory: true
alternatesporthistory: true
altuspoliticsproject: true
altverse: true
alwiki: true
amazingyoutubers: true
anachronoxwiki: true
ancyclopedia: true
andusan: true
angelwise: true
aniwotawiki: true
anothereden: true
antrozoologia: true
apcwiki: 'www.apcwiki.org'
apneuvereniging: true
apuntes: true
arefepva: true
arphilosophy: true
ar: true
asgyaanipedia: true
astrobiology: 'encyclopediaofastrobiology.org'
atlasinternational: true
atm: true
atpl: true
atrociousdeviants: true
atrociousfandomusers: true
atrociousyoutubers: true
australiasim: true
awesomegames: true
awfulmovies: true
ayrshire: true
ayurbooks: true
basura: true
bch: true
bearwiki: true
besttvshows: true
betapurple: true
bgo: true
biblicalwiki: true
bigcartoon: true
bigforest: true
bildung: true
biu: true
blepia: true
blooperwiki: true
bloowiki: true
bngyaanipedia: 'bn.gyaanipedia.co.in'
bogdan: true
bonessdiving: 'wiki.bonessdiving.club'
bonziworld: true
borost: true
bpa: true
breedersofthenephelym: true
browndust: true
brynda1231: true
bsc: true
bst: true
bubba: true
buddypedia: true
bullshitsystems: 'wiki.bullshit.systems'
bunker401: true
bus: true
byblopedia: true
caestaron: true
calibro: true
campaignlab: 'wiki.campaign-labour.org'
cantorij: true
cartesium: true
carvalhopedia: 'wiki.casadocarvalho.net'
casuarina: true
cbhssjb: true
cccp: true
cdc: true
central: true
chimaera: true
christipedia: true
civclassic: true
civitas: true
ckc: true
clineclass: true
cloudconstruct: true
cmhoc: true
cnv: true
codexamica: true
combinerebjigglywiki: true
commonsgyaanipedia: 'commons.gyaanipedia.co.in'
commonswiki: true
communitycentralbympteam: true
communitydirectedsupport: true
concepts: true
conseildesvoleurs: true
conservapedia: true
conservipedia: true
const: true
corepedia: true
corro: true
corsarius: true
corydoctorow: true
craedopedia: true
crappygames: true
crazybloxianempireinfo: true
credco: true
crest: true
crimescience: 'crimesciencewiki.org'
critalenca: true
csnimsbordeaux: true
ctfoundry: true
cuttingroom: true
cyberlaw: true
dakhilcommunity: true
dalar: true
decrypted: 'decrypted.wiki'
destinos: true
diaroleplays: true
didapro: 'encyclopedie.didactiqueprofessionnelle.org'
differenthistory: true
dish: true
dobots: 'wiki.dobots.nl'
dofo: true
doin: true
doomsdaydebunked: true
dragpedia: 'drag.lgbt'
dreddbook: true
drones4all: 'wiki.drones4nature.info'
dwe: true
dwplive: 'wiki.dwplive.com'
dyrn: true
eaddemos: true
earthian: true
ecoepi: true
ecype: true
edw: true
eerstelijnszones: 'www.eerstelijnszones.be'
electowiki: 'electowiki.org'
elpoderdelpueblo: true
encyclopediaikonia: true
encyclopediainsania: true
encyclopediamemeia: true
encyclopedia: true
enigma: true
environmentaljustice: true
eon: true
epicerieissy: true
epicseven: true
espiral: 'espiral.org'
eva: true
exocortex: 'exocortex.sillyendpoints.com'
fagyaanipedia: 'fa.gyaanipedia.co.in'
fantasia: true
ferahistoria: true
feu: 'froggy.info'
fictionfoundry: true
fifam: true
fikcyjnatv: true
fkkfan: true
flawlessfandomusers: true
fluxordev: true
fmbv: true
fna: true
foodsharinghamburg: true
forbidden: true
fortnite: true
freevandalism: true
futurewiki: true
gasepedia: true
geirpedia: true
genealog: true
genship: true
gen: true
gepacoassoculture: true
gepacobiodiv: true
gfi: true
ghhs: true
giantess: true
giletjaune: true
gipedia: true
gkatom: true