2b2t: true
50beardsofgrey: true
690squadron: true
abortopedia: true
absurdopedia: true
abysmalrobloxgames: true
acqint: true
adlc: true
aebyp: true
aeross: true
afterworld: true
agilebook: true
aisg: true
aktpos: true
alanoccv: true
ale: true
algopedia: true
algowiki: true
allthetropes: 'allthetropes.org'
allwikis: true
alternatehistory: true
alternatesporthistory: true
altuspoliticsproject: true
altverse: true
alwiki: true
amazingyoutubers: true
anachronoxwiki: true
ancyclopedia: true
andusan: true
angelwise: true
animanga: true
animeshoes: true
aniwotawiki: true
anothereden: true
antrozoologia: true
apcwiki: 'www.apcwiki.org'
apneuvereniging: true
apuntes: true
arefepva: true
arphilosophy: true
ar: true
asgyaanipedia: true